// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"chapapp-backend-api/internal/controller"
	"chapapp-backend-api/internal/reporitory"
	"chapapp-backend-api/internal/service"
)

// Injectors from auth.wire.go:

func InitModuleAuth() (*controller.AuthController, error) {
	iAccountRepository := reporitory.NewAccountRepository()
	iAuthRepository := reporitory.NewAuthRepository()
	iAuthService := service.NewAuthService(iAccountRepository, iAuthRepository)
	authController := controller.NewAuthController(iAuthService)
	return authController, nil
}
