// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePerson = "persons"

// Person mapped from table <persons>
type Person struct {
	Personid  int32  `gorm:"column:Personid;primaryKey;autoIncrement:true" json:"Personid"`
	LastName  string `gorm:"column:LastName;not null" json:"LastName"`
	FirstName string `gorm:"column:FirstName" json:"FirstName"`
	Age       int32  `gorm:"column:Age" json:"Age"`
}

// TableName Person's table name
func (*Person) TableName() string {
	return TableNamePerson
}
