server:
  mode: "production"
  port: 8080
  socketPort: 8081

cors:
  url: "http://localhost:5173"  # Nếu frontend chạy local, giữ nguyên

mysql:
  host: "mysql-docker"     # tên service trong docker-compose
  port: 3306
  username: "root"
  password: "nguyenvu"
  dbname: "chatapp"
  maxIdleConns: 3
  maxOpenConns: 5
  connMaxLifeTime: 10

redis:
  host: "redis"     # tên service trong docker-compose
  port: 6379
  password: ""
  database: 0

log:
  logLevel: "debug"
  fileLogName: "./storage/logs/server.log"  # log vẫn ghi vào trong container (mount ra nếu cần)
  maxSize:    500
  maxBackups: 3
  maxAge:     7
  compress:   true

jwt:
  accessSecret: "myaccessecrettoken2025"
  accessSecretExpiriedTime: 3600
  refreshSecret: "myrefreshtokensecret2025"
  refreshSecretExpiriedTime: 86400

cloudinary:
  cloud_name: "dmsnw2qpd"
  api_key: "214187186256291"
  api_secret: "13ew1sxffolXvVYkaGleJcAd4AY"

admin:
  email: "toilaadmin@gmail.com"
  username: "toilaadmin"
  phoneNumber: "0012345621"
  password: "Toilaadmin@2004"

